[[copt]]
arch = "aarch64"
os = "linux"
git-tree-sha1 = "a4659be681eba1ba37a9e2bb4f237e738afe1961"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.3/aarch64/CardinalOptimizer-8.0.3-aarch64_lnx.tar.gz"
    sha256 = "0306b52d14de217ec80dd9e6aaf51353d415a217a4f43a13f355b4bdfc010d49"

[[copt]]
arch = "aarch64"
os = "macos"
git-tree-sha1 = "ef8baaacccd889d1fee52d698e07dfeefd8de6d0"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.3/osx64/CardinalOptimizer-8.0.3-universal_mac.tar.gz"
    sha256 = "f340bfde55a7e9e17cbe8be5e8699936eab4232f8565404f92237f47f58bbca5"

[[copt]]
arch = "x86_64"
os = "linux"
git-tree-sha1 = "0efc1c8fe4fffbebdd6d5e1f025b09467e3b3faa"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.3/linux64/CardinalOptimizer-8.0.3-lnx64.tar.gz"
    sha256 = "381a833b17b78b27defded54a37be96c6fe162b6de1d10107fc336921bc2a6d3"

[[copt]]
arch = "x86_64"
os = "macos"
git-tree-sha1 = "ef8baaacccd889d1fee52d698e07dfeefd8de6d0"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.3/osx64/CardinalOptimizer-8.0.3-universal_mac.tar.gz"
    sha256 = "f340bfde55a7e9e17cbe8be5e8699936eab4232f8565404f92237f47f58bbca5"

[[copt]]
arch = "x86_64"
os = "windows"
git-tree-sha1 = "bbc3fdfc598d388fb8dc743ecab6c8b52b1d4bbf"
lazy = true

    [[copt.download]]
    url = "https://pub.shanshu.ai/download/copt/8.0.3/win64/CardinalOptimizer-8.0.3-win64.tar.gz"
    sha256 = "6da985895c58d086a2e923e00bb21c20ea7b7af007fa83173acbe04f3c25f0fe"

